export type Country = {
  code: string;
  name: string;
  flag: string;
  defaultLanguage: string;
  lawSummary: string;
};

/** Full ISO 3166-1 country list for jurisdiction selection. */
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", defaultLanguage: "en", lawSummary: "Constitution and statutory codes" },
  { code: "AL", name: "Albania", flag: "🇦🇱", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned reforms" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", defaultLanguage: "ar", lawSummary: "Civil code and constitutional law" },
  { code: "AD", name: "Andorra", flag: "🇦🇩", defaultLanguage: "es", lawSummary: "Civil-law statutes and ordinances" },
  { code: "AO", name: "Angola", flag: "🇦🇴", defaultLanguage: "pt", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", defaultLanguage: "es", lawSummary: "Civil code, constitution, and federal statutes" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional court practice" },
  { code: "AU", name: "Australia", flag: "🇦🇺", defaultLanguage: "en", lawSummary: "Commonwealth and state legislation with common-law precedent" },
  { code: "AT", name: "Austria", flag: "🇦🇹", defaultLanguage: "de", lawSummary: "Civil code, constitutional law, and EU-aligned rules" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean case law" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", defaultLanguage: "ar", lawSummary: "Civil and commercial codes with Sharia-influenced rules" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "BB", name: "Barbados", flag: "🇧🇧", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", defaultLanguage: "fr", lawSummary: "Civil code, federal statutes, and EU law" },
  { code: "BZ", name: "Belize", flag: "🇧🇿", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean practice" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", defaultLanguage: "en", lawSummary: "Constitutional and statutory framework" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", defaultLanguage: "es", lawSummary: "Civil code and constitutional law" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", defaultLanguage: "en", lawSummary: "Civil-law codes and entity-level statutes" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", defaultLanguage: "pt", lawSummary: "Federal constitution, civil code, and Superior Court decisions" },
  { code: "BN", name: "Brunei", flag: "🇧🇳", defaultLanguage: "en", lawSummary: "Common-law statutes with Sharia elements" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", defaultLanguage: "fr", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", defaultLanguage: "pt", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", defaultLanguage: "en", lawSummary: "Civil code and constitutional statutes" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", defaultLanguage: "fr", lawSummary: "Mixed common/civil law and OHADA rules" },
  { code: "CA", name: "Canada", flag: "🇨🇦", defaultLanguage: "en", lawSummary: "Federal and provincial statutes, common law and civil law (Québec)" },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "TD", name: "Chad", flag: "🇹🇩", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "CL", name: "Chile", flag: "🇨🇱", defaultLanguage: "es", lawSummary: "Civil code and constitutional jurisprudence" },
  { code: "CN", name: "China", flag: "🇨🇳", defaultLanguage: "zh", lawSummary: "Civil code, statutes, and Supreme People’s Court guidance" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", defaultLanguage: "es", lawSummary: "Civil code, constitution, and Constitutional Court practice" },
  { code: "KM", name: "Comoros", flag: "🇰🇲", defaultLanguage: "fr", lawSummary: "Civil-law and Islamic-influenced statutes" },
  { code: "CG", name: "Congo", flag: "🇨🇬", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "CI", name: "Côte d’Ivoire", flag: "🇨🇮", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", defaultLanguage: "es", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", defaultLanguage: "en", lawSummary: "Common-law statutes and EU-aligned rules" },
  { code: "CZ", name: "Czechia", flag: "🇨🇿", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", defaultLanguage: "en", lawSummary: "Civil-law statutes and EU-aligned rules" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", defaultLanguage: "fr", lawSummary: "Civil-law codes and commercial statutes" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", defaultLanguage: "es", lawSummary: "Civil code and constitutional law" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", defaultLanguage: "ar", lawSummary: "Civil code, commercial codes, and constitutional law" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", defaultLanguage: "es", lawSummary: "Civil code and constitutional statutes" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", defaultLanguage: "es", lawSummary: "Civil-law codes and OHADA-influenced practice" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", defaultLanguage: "en", lawSummary: "Civil code and constitutional framework" },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific jurisprudence" },
  { code: "FI", name: "Finland", flag: "🇫🇮", defaultLanguage: "en", lawSummary: "Civil-law statutes and EU-aligned rules" },
  { code: "FR", name: "France", flag: "🇫🇷", defaultLanguage: "fr", lawSummary: "Civil code, constitutional law, and administrative sources" },
  { code: "GA", name: "Gabon", flag: "🇬🇦", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "DE", name: "Germany", flag: "🇩🇪", defaultLanguage: "de", lawSummary: "Civil code (BGB), Basic Law, and EU-aligned regulations" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "GR", name: "Greece", flag: "🇬🇷", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", defaultLanguage: "pt", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean practice" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", defaultLanguage: "fr", lawSummary: "Civil code and constitutional statutes" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", defaultLanguage: "en", lawSummary: "Civil-law statutes and EEA-aligned rules" },
  { code: "IN", name: "India", flag: "🇮🇳", defaultLanguage: "en", lawSummary: "Constitution, central acts, and High Court / Supreme Court precedent" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "IR", name: "Iran", flag: "🇮🇷", defaultLanguage: "fa", lawSummary: "Civil code with Islamic-law principles" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", defaultLanguage: "ar", lawSummary: "Civil code and constitutional framework" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", defaultLanguage: "en", lawSummary: "Common-law statutes, constitution, and EU law" },
  { code: "IL", name: "Israel", flag: "🇮🇱", defaultLanguage: "he", lawSummary: "Basic Laws, statutes, and Supreme Court jurisprudence" },
  { code: "IT", name: "Italy", flag: "🇮🇹", defaultLanguage: "it", lawSummary: "Civil code, constitution, and EU-aligned legislation" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "JP", name: "Japan", flag: "🇯🇵", defaultLanguage: "ja", lawSummary: "Civil code, statutes, and Supreme Court decisions" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", defaultLanguage: "ar", lawSummary: "Civil code and constitutional framework" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", defaultLanguage: "ar", lawSummary: "Civil and commercial codes with Sharia-influenced rules" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "LA", name: "Laos", flag: "🇱🇦", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", defaultLanguage: "ar", lawSummary: "Civil code and mixed personal-status rules" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "LY", name: "Libya", flag: "🇱🇾", defaultLanguage: "ar", lawSummary: "Civil code and constitutional statutes" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", defaultLanguage: "de", lawSummary: "Civil-law codes and EEA-aligned rules" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", defaultLanguage: "fr", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", defaultLanguage: "fr", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", defaultLanguage: "en", lawSummary: "Common-law statutes with Islamic personal law" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", defaultLanguage: "en", lawSummary: "Civil and Islamic-influenced statutory framework" },
  { code: "ML", name: "Mali", flag: "🇲🇱", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "MT", name: "Malta", flag: "🇲🇹", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", defaultLanguage: "ar", lawSummary: "Civil-law and Islamic-influenced statutes" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", defaultLanguage: "en", lawSummary: "Mixed civil/common-law statutes" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", defaultLanguage: "es", lawSummary: "Federal civil code, constitution, and amparo jurisprudence" },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", defaultLanguage: "fr", lawSummary: "Civil-law codes and ordinances" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned reforms" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", defaultLanguage: "ar", lawSummary: "Civil code, commercial codes, and constitutional law" },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", defaultLanguage: "pt", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", defaultLanguage: "en", lawSummary: "Statutory codes and constitutional framework" },
  { code: "NA", name: "Namibia", flag: "🇳🇦", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", defaultLanguage: "en", lawSummary: "Civil code and constitutional framework" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", defaultLanguage: "nl", lawSummary: "Civil code, EU law, and administrative jurisprudence" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", defaultLanguage: "en", lawSummary: "Common-law statutes and parliamentary legislation" },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "NE", name: "Niger", flag: "🇳🇪", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", defaultLanguage: "en", lawSummary: "Common-law statutes, federal acts, and customary law" },
  { code: "KP", name: "North Korea", flag: "🇰🇵", defaultLanguage: "ko", lawSummary: "Socialist statutory codes" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned reforms" },
  { code: "NO", name: "Norway", flag: "🇳🇴", defaultLanguage: "en", lawSummary: "Civil-law statutes and EEA-aligned rules" },
  { code: "OM", name: "Oman", flag: "🇴🇲", defaultLanguage: "ar", lawSummary: "Civil and commercial codes with Sharia principles" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", defaultLanguage: "en", lawSummary: "Common-law statutes with Islamic personal law" },
  { code: "PW", name: "Palau", flag: "🇵🇼", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "PS", name: "Palestine", flag: "🇵🇸", defaultLanguage: "ar", lawSummary: "Civil-law codes and statutory framework" },
  { code: "PA", name: "Panama", flag: "🇵🇦", defaultLanguage: "es", lawSummary: "Civil code and commercial statutes" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "PE", name: "Peru", flag: "🇵🇪", defaultLanguage: "es", lawSummary: "Civil code and constitutional jurisprudence" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", defaultLanguage: "en", lawSummary: "Civil code, constitution, and Supreme Court decisions" },
  { code: "PL", name: "Poland", flag: "🇵🇱", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", defaultLanguage: "pt", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", defaultLanguage: "ar", lawSummary: "Civil and commercial codes with Sharia-influenced rules" },
  { code: "RO", name: "Romania", flag: "🇷🇴", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "RU", name: "Russia", flag: "🇷🇺", defaultLanguage: "ru", lawSummary: "Civil code and constitutional statutes" },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", defaultLanguage: "en", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", defaultLanguage: "en", lawSummary: "Mixed civil/common-law Caribbean statutes" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", defaultLanguage: "it", lawSummary: "Civil-law codes and statutes" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", defaultLanguage: "pt", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", defaultLanguage: "ar", lawSummary: "Basic Law, Sharia principles, and recent commercial reforms" },
  { code: "SN", name: "Senegal", flag: "🇸🇳", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned reforms" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", defaultLanguage: "en", lawSummary: "Mixed civil/common-law statutes" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", defaultLanguage: "en", lawSummary: "Statutes, common law, and specialized commercial regulations" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", defaultLanguage: "en", lawSummary: "Civil code and EU-aligned legislation" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", defaultLanguage: "en", lawSummary: "Civil-law codes and EU-aligned legislation" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", defaultLanguage: "en", lawSummary: "Common-law statutes and customary-law interaction" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", defaultLanguage: "ar", lawSummary: "Mixed civil, customary, and Islamic-influenced rules" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", defaultLanguage: "en", lawSummary: "Constitution, statutes, and common-law precedent" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", defaultLanguage: "ko", lawSummary: "Civil code, statutes, and Constitutional Court practice" },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "ES", name: "Spain", flag: "🇪🇸", defaultLanguage: "es", lawSummary: "Civil code, constitution, and EU-aligned legislation" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", defaultLanguage: "en", lawSummary: "Mixed Roman-Dutch and common-law statutes" },
  { code: "SD", name: "Sudan", flag: "🇸🇩", defaultLanguage: "ar", lawSummary: "Civil and Islamic-influenced statutory framework" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", defaultLanguage: "nl", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", defaultLanguage: "en", lawSummary: "Civil-law statutes and EU-aligned rules" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", defaultLanguage: "de", lawSummary: "Civil code, federal statutes, and cantonal law" },
  { code: "SY", name: "Syria", flag: "🇸🇾", defaultLanguage: "ar", lawSummary: "Civil code and constitutional statutes" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", defaultLanguage: "zh", lawSummary: "Civil code, statutes, and judicial interpretations" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", defaultLanguage: "en", lawSummary: "Civil and commercial codes" },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", defaultLanguage: "pt", lawSummary: "Civil-law codes and constitutional framework" },
  { code: "TG", name: "Togo", flag: "🇹🇬", defaultLanguage: "fr", lawSummary: "Civil-law codes and OHADA commercial rules" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", defaultLanguage: "en", lawSummary: "Common-law statutes and Caribbean jurisprudence" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", defaultLanguage: "ar", lawSummary: "Civil code and constitutional framework" },
  { code: "TR", name: "Türkiye", flag: "🇹🇷", defaultLanguage: "tr", lawSummary: "Civil code, constitution, and commercial statutes" },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", defaultLanguage: "en", lawSummary: "Common-law statutes and Pacific practice" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", defaultLanguage: "en", lawSummary: "Civil code and constitutional statutes" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", defaultLanguage: "ar", lawSummary: "Federal laws, free-zone regulations, and Sharia-influenced civil codes" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", defaultLanguage: "en", lawSummary: "Common law, Acts of Parliament, and secondary legislation" },
  { code: "US", name: "United States", flag: "🇺🇸", defaultLanguage: "en", lawSummary: "Federal statutes, case law, and state-specific codes" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", defaultLanguage: "ru", lawSummary: "Civil-law codes and constitutional statutes" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", defaultLanguage: "en", lawSummary: "Mixed common/civil-law and customary practice" },
  { code: "VA", name: "Vatican City", flag: "🇻🇦", defaultLanguage: "it", lawSummary: "Canon law and Lateran statutes" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", defaultLanguage: "es", lawSummary: "Civil code and constitutional framework" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", defaultLanguage: "en", lawSummary: "Civil code and constitutional statutes" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", defaultLanguage: "ar", lawSummary: "Civil and Islamic-influenced statutory framework" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", defaultLanguage: "en", lawSummary: "Common-law statutes and constitutional framework" },
].sort((a, b) => a.name.localeCompare(b.name));

export function getCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function searchCountries(query: string): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.code.toLowerCase().includes(q)
  );
}
